TablaAudios = {}

function audioLoad()
    a = love.audio.newSource("Audios/a.wav", "static")
    table.insert(TablaAudios, a)
    b = love.audio.newSource("Audios/b.wav", "static")
    table.insert(TablaAudios, b)
    c = love.audio.newSource("Audios/c.wav", "static")
    table.insert(TablaAudios, c)
    d = love.audio.newSource("Audios/d.wav", "static")
    table.insert(TablaAudios, d)
    e = love.audio.newSource("Audios/e.wav", "static")
    table.insert(TablaAudios, e)
    f = love.audio.newSource("Audios/f.wav", "static")
    table.insert(TablaAudios, f)
    g = love.audio.newSource("Audios/g.wav", "static")
    table.insert(TablaAudios, g)
    h = love.audio.newSource("Audios/h.wav", "static")
    table.insert(TablaAudios, h)
    i = love.audio.newSource("Audios/i.wav", "static")
    table.insert(TablaAudios, i)
    j = love.audio.newSource("Audios/j.wav", "static")
    table.insert(TablaAudios, j)
end

function audioSound()
    Random = love.math.random(1, #TablaAudios)
    TablaAudios[Random]:play()
    TablaAudios[Random]:setPitch(1)
end
